# Generated by Django 4.1.7 on 2023-03-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("std", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="phone",
            new_name="contact",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="address",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="roll",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="email",
            new_name="time",
        ),
    ]
